### ISSUE TITLE
Markdown 2.5 breaks OSQA (ImportError of BADGES_SET and Question)

### ISSUE THREAD

**Issue by ncouture** [dzone/osqa#81]
I have experienced the same issue described in #79 using the [revision 1080](https://github.com/dzone/osqa/tree/a60778963b1e3a694c83e6629b001cfc05918ad6) of OSQA and was able to resolve it by installing an older version of Markdown==2.4.1

This ultimately results in the following exceptions:
```
./forum/modules/__init__.py TIME: 2014-11-30 19:34:23,364 MSG: __init__.py:get_modules_script:22 Error importing settings from module <module 'osqa.forum_modules.updates' from '/var/www/osqa/forum_modules/updates/__init__.pyc'>
Traceback (most recent call last):
  File "./forum/modules/__init__.py", line 18, in get_modules_script
    all.append(__import__('%s.%s' % (m.__name__, script_name), globals(), locals(), [m.__name__]))
  File "/var/www/osqa/forum_modules/updates/settings.py", line 6, in <module>
    from base import generate_installation_key
  File "/var/www/osqa/forum_modules/updates/base.py", line 20, in <module>
    from forum.models import Question, Answer, Comment, User
ImportError: cannot import name Question
./forum/modules/__init__.py TIME: 2014-11-30 19:34:23,365 MSG: __init__.py:get_modules_script:22 Error importing settings from module <module 'osqa.forum_modules.default_badges' from '/var/www/osqa/forum_modules/default_badges/__init__.pyc'>
Traceback (most recent call last):
  File "./forum/modules/__init__.py", line 18, in get_modules_script
    all.append(__import__('%s.%s' % (m.__name__, script_name), globals(), locals(), [m.__name__]))
  File "/var/www/osqa/forum_modules/default_badges/settings.py", line 4, in <module>
    from forum.settings import BADGES_SET
ImportError: cannot import name BADGES_SET
```

Here is the full traceback:
```
/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py TIME: 2014-11-30 19:27:19,900 MSG: __init__.py:build_extension:245 Successfuly imported extension module "mdx_settingsparser".
/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/core/handlers/base.py TIME: 2014-11-30 19:27:19,901 MSG: base.py:handle_uncaught_exception:226 Internal Server Error: /
Traceback (most recent call last):
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./forum/modules/decorators.py", line 95, in decorated
    return decoratable(*args, **kwargs)
  File "./forum/modules/decorators.py", line 60, in __call__
    res = dec(res, *args, **kwargs)
  File "./forum/views/decorators.py", line 35, in decorated
    context_instance=RequestContext(request))
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py",
line 134, in _render
    return self.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "./forum/templatetags/general_sidebar_tags.py", line 21, in sidebar_upper
    'content': static_content(settings.SIDEBAR_UPPER_TEXT, settings.SIDEBAR_UPPER_RENDER_MODE),
  File "./forum/templatetags/extra_filters.py", line 59, in static_content
    return mark_safe(markdown.markdown(unicode(content), ["settingsparser"]))
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 464, in markdown
    md = Markdown(*args, **kwargs)
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 154, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 180, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 265, in build_extension
    return module.makeExtension(**configs)
  File "./forum/markdownext/mdx_settingsparser.py", line 46, in makeExtension
    return SettingsExtension(configs=configs)
  File "./forum/markdownext/mdx_settingsparser.py", line 13, in __init__
    for key, value in configs:
TypeError: 'NoneType' object is not iterable
./forum/views/meta.py TIME: 2014-11-30 19:27:19,903 MSG: meta.py:error_handler:202 
        error executing request:
        PATH: /
        USER: <anonymous>
        METHOD: GET
        POST PARAMETERS:
        None
        GET PARAMETERS:
        None
        HTTP HEADERS:
                        wsgi.multiprocess: True
                HTTP_COOKIE: _csrf=tATUdeJAvuCAuNmotICioOlOlbonBInBailaaaRWJpx; askbot_visitor=False; __utma=222975773.1055636710.1417366862.1417382632.1417387078.5; __utmc=222975773; __utmz=222975773.1417366862.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); sessionid=npsallo9jpipixty2k5c4c41tdqm6ydx; greeting_set=True; csrftoken=0qtaS10845356masddkgfttVxyX1pQWMiZ
                SCRIPT_NAME: 
                REQUEST_METHOD: GET
                PATH_INFO: /
                SERVER_PROTOCOL: HTTP/1.1
                QUERY_STRING: 
                CONTENT_LENGTH: 
                HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
                HTTP_CONNECTION: keep-alive
                SERVER_NAME: example.com
                REMOTE_ADDR: 127.0.0.1
                wsgi.url_scheme: http
                SERVER_PORT: 80
                uwsgi.node: hostname.invalid
                DOCUMENT_ROOT: /usr/share/nginx/html
                wsgi.input: <uwsgi._Input object at 0x7f670d042060>
                HTTP_HOST: example.com
                wsgi.multithread: False
                HTTP_CACHE_CONTROL: max-age=0
                REQUEST_URI: /
                HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                wsgi.version: (1, 0)
                wsgi.run_once: False
                wsgi.errors: <open file 'wsgi_errors', mode 'w' at 0x7f670fe58db0>
                REMOTE_PORT: 52503
                HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.8
                CSRF_COOKIE_USED: True
                uwsgi.version: 2.0.7-debian
                CONTENT_TYPE: 
                wsgi.file_wrapper: <built-in function uwsgi_sendfile>
                CSRF_COOKIE: 0qtaS1086iMaF848MYKvLmkVX1pQWMiZ
                HTTP_ACCEPT_ENCODING: gzip,deflate,sdch

        COOKIES:
                        __utmz: 222975773.1417366862.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
                askbot_visitor: False
                csrftoken: 0qtaS1fdgh06686i76KvLmk12pQWMiZ
                sessionid: npsmk6mw9jbjj498dhfdsklHduetdqm6ydx
                _csrf: lV6gvTlkS1fdgh0kwOLpBKVTYkzRWJpx
                __utma: 222975772.10551236710.1417366862.1417382632.1417387078.5
                __utmc: 222975772
                greeting_set: True

        EXCEPTION INFO:
                        Traceback (most recent call last):
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs)
                  File "./forum/modules/decorators.py", line 95, in decorated
                    return decoratable(*args, **kwargs)
                  File "./forum/modules/decorators.py", line 60, in __call__
                    res = dec(res, *args, **kwargs)
                  File "./forum/views/decorators.py", line 35, in decorated
                    context_instance=RequestContext(request))
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
                    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
                    return t.render(context_instance)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
                    return self._render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
                    return self.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
                    return compiled_parent._render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
                    return self.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
                    return compiled_parent._render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
                    return self.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
                    return compiled_parent._render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
                    return self.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
                    result = block.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
                    result = block.nodelist.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
                    bit = self.render_node(node, context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
                    return node.render(context)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/django/template/base.py", line 1196, in render
                    _dict = func(*resolved_args, **resolved_kwargs)
                  File "./forum/templatetags/general_sidebar_tags.py", line 21, in sidebar_upper
                    'content': static_content(settings.SIDEBAR_UPPER_TEXT, settings.SIDEBAR_UPPER_RENDER_MODE),
                  File "./forum/templatetags/extra_filters.py", line 59, in static_content
                    return mark_safe(markdown.markdown(unicode(content), ["settingsparser"]))
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 464, in markdown
                    md = Markdown(*args, **kwargs)
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 154, in __init__
                    configs=kwargs.get('extension_configs', {}))
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 180, in registerExtensions
                    ext = self.build_extension(ext, configs.get(ext, {}))
                  File "/home/self/.virtualenvs/osqa/local/lib/python2.7/site-packages/markdown/__init__.py", line 265, in build_extension
                    return module.makeExtension(**configs)
                  File "./forum/markdownext/mdx_settingsparser.py", line 46, in makeExtension
                    return SettingsExtension(configs=configs)
                  File "./forum/markdownext/mdx_settingsparser.py", line 13, in __init__
                    for key, value in configs:
                TypeError: 'NoneType' object is not iterable
```

**Comment by jvsteiner** [comment]
changing line 46 in ./forum/markdownext/mdx_settingsparser.py from:
`def makeExtension(configs=None):`
to:
`def makeExtension(configs={}):`
worked for me

**Comment by SparkandShine** [comment]
This works for me.

`Found existing installation: Markdown 2.6.2`
